// Mocks generated by Mockito 5.4.6 from annotations
// in stock_investment_tracker/test/data/repositories/lot_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stock_investment_tracker/data/data_sources/remote/firestore_data_source.dart'
    as _i2;
import 'package:stock_investment_tracker/data/models/lot_model.dart' as _i4;
import 'package:stock_investment_tracker/data/models/sale_model.dart' as _i5;
import 'package:stock_investment_tracker/data/models/user_settings_model.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirestoreDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreDataSource extends _i1.Mock
    implements _i2.FirestoreDataSource {
  MockFirestoreDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.LotModel>> watchAllLots(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllLots, [uid]),
            returnValue: _i3.Stream<List<_i4.LotModel>>.empty(),
          )
          as _i3.Stream<List<_i4.LotModel>>);

  @override
  _i3.Future<void> addLot(String? uid, _i4.LotModel? lot) =>
      (super.noSuchMethod(
            Invocation.method(#addLot, [uid, lot]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLot(String? uid, _i4.LotModel? lot) =>
      (super.noSuchMethod(
            Invocation.method(#updateLot, [uid, lot]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLot(String? uid, String? lotId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLot, [uid, lotId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i5.SaleModel>> watchAllSales(String? uid, String? lotId) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllSales, [uid, lotId]),
            returnValue: _i3.Stream<List<_i5.SaleModel>>.empty(),
          )
          as _i3.Stream<List<_i5.SaleModel>>);

  @override
  _i3.Future<void> addSale(String? uid, String? lotId, _i5.SaleModel? sale) =>
      (super.noSuchMethod(
            Invocation.method(#addSale, [uid, lotId, sale]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSale(
    String? uid,
    String? lotId,
    _i5.SaleModel? sale,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSale, [uid, lotId, sale]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSale(String? uid, String? lotId, String? saleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSale, [uid, lotId, saleId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i6.UserSettingsModel?> watchSettings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchSettings, [uid]),
            returnValue: _i3.Stream<_i6.UserSettingsModel?>.empty(),
          )
          as _i3.Stream<_i6.UserSettingsModel?>);

  @override
  _i3.Future<void> updateSettings(
    String? uid,
    _i6.UserSettingsModel? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [uid, settings]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
