// Mocks generated by Mockito 5.4.6 from annotations
// in stock_investment_tracker/test/data/repositories/market_price_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stock_investment_tracker/data/data_sources/local/hive_data_source.dart'
    as _i11;
import 'package:stock_investment_tracker/data/data_sources/remote/firestore_data_source.dart'
    as _i2;
import 'package:stock_investment_tracker/data/models/lot_model.dart' as _i4;
import 'package:stock_investment_tracker/data/models/market_price_model.dart'
    as _i9;
import 'package:stock_investment_tracker/data/models/position_model.dart'
    as _i5;
import 'package:stock_investment_tracker/data/models/price_alert_model.dart'
    as _i10;
import 'package:stock_investment_tracker/data/models/sale_model.dart' as _i6;
import 'package:stock_investment_tracker/data/models/user_settings_model.dart'
    as _i8;
import 'package:stock_investment_tracker/data/models/withdrawal_model.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirestoreDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreDataSource extends _i1.Mock
    implements _i2.FirestoreDataSource {
  MockFirestoreDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.LotModel>> watchAllLots(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllLots, [uid]),
            returnValue: _i3.Stream<List<_i4.LotModel>>.empty(),
          )
          as _i3.Stream<List<_i4.LotModel>>);

  @override
  _i3.Future<void> addLot(String? uid, _i4.LotModel? lot) =>
      (super.noSuchMethod(
            Invocation.method(#addLot, [uid, lot]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLot(String? uid, _i4.LotModel? lot) =>
      (super.noSuchMethod(
            Invocation.method(#updateLot, [uid, lot]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLot(String? uid, String? lotId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLot, [uid, lotId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i5.PositionModel>> watchAllPositions(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllPositions, [uid]),
            returnValue: _i3.Stream<List<_i5.PositionModel>>.empty(),
          )
          as _i3.Stream<List<_i5.PositionModel>>);

  @override
  _i3.Future<void> addPosition(String? uid, _i5.PositionModel? position) =>
      (super.noSuchMethod(
            Invocation.method(#addPosition, [uid, position]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updatePosition(String? uid, _i5.PositionModel? position) =>
      (super.noSuchMethod(
            Invocation.method(#updatePosition, [uid, position]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePosition(String? uid, String? positionId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePosition, [uid, positionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i6.SaleModel>> watchAllSales(String? uid, String? lotId) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllSales, [uid, lotId]),
            returnValue: _i3.Stream<List<_i6.SaleModel>>.empty(),
          )
          as _i3.Stream<List<_i6.SaleModel>>);

  @override
  _i3.Future<void> addSale(String? uid, String? lotId, _i6.SaleModel? sale) =>
      (super.noSuchMethod(
            Invocation.method(#addSale, [uid, lotId, sale]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSale(
    String? uid,
    String? lotId,
    _i6.SaleModel? sale,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSale, [uid, lotId, sale]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSale(String? uid, String? lotId, String? saleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSale, [uid, lotId, saleId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int?> getUserSchemaVersion(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserSchemaVersion, [uid]),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<List<_i4.LotModel>> getAllLotsOnce(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getAllLotsOnce, [uid]),
            returnValue: _i3.Future<List<_i4.LotModel>>.value(<_i4.LotModel>[]),
          )
          as _i3.Future<List<_i4.LotModel>>);

  @override
  _i3.Future<void> stampSchemaVersion(String? uid, int? version) =>
      (super.noSuchMethod(
            Invocation.method(#stampSchemaVersion, [uid, version]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> runPositionMigrationBatches(
    String? uid,
    List<_i5.PositionModel>? positions,
    int? version,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#runPositionMigrationBatches, [
              uid,
              positions,
              version,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i7.WithdrawalModel>> watchAllWithdrawals(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllWithdrawals, [uid]),
            returnValue: _i3.Stream<List<_i7.WithdrawalModel>>.empty(),
          )
          as _i3.Stream<List<_i7.WithdrawalModel>>);

  @override
  _i3.Future<void> addWithdrawal(
    String? uid,
    _i7.WithdrawalModel? withdrawal,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addWithdrawal, [uid, withdrawal]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateWithdrawal(
    String? uid,
    _i7.WithdrawalModel? withdrawal,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWithdrawal, [uid, withdrawal]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteWithdrawal(String? uid, String? withdrawalId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWithdrawal, [uid, withdrawalId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i8.UserSettingsModel?> watchSettings(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchSettings, [uid]),
            returnValue: _i3.Stream<_i8.UserSettingsModel?>.empty(),
          )
          as _i3.Stream<_i8.UserSettingsModel?>);

  @override
  _i3.Future<void> updateSettings(
    String? uid,
    _i8.UserSettingsModel? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [uid, settings]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i9.MarketPriceModel?> watchMarketPrice(String? ticker) =>
      (super.noSuchMethod(
            Invocation.method(#watchMarketPrice, [ticker]),
            returnValue: _i3.Stream<_i9.MarketPriceModel?>.empty(),
          )
          as _i3.Stream<_i9.MarketPriceModel?>);

  @override
  _i3.Stream<List<_i9.MarketPriceModel>> watchMarketPrices(
    List<String>? tickers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMarketPrices, [tickers]),
            returnValue: _i3.Stream<List<_i9.MarketPriceModel>>.empty(),
          )
          as _i3.Stream<List<_i9.MarketPriceModel>>);

  @override
  _i3.Stream<List<_i10.PriceAlertModel>> watchAllPriceAlerts(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllPriceAlerts, [uid]),
            returnValue: _i3.Stream<List<_i10.PriceAlertModel>>.empty(),
          )
          as _i3.Stream<List<_i10.PriceAlertModel>>);

  @override
  _i3.Future<void> addPriceAlert(String? uid, _i10.PriceAlertModel? alert) =>
      (super.noSuchMethod(
            Invocation.method(#addPriceAlert, [uid, alert]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updatePriceAlert(String? uid, _i10.PriceAlertModel? alert) =>
      (super.noSuchMethod(
            Invocation.method(#updatePriceAlert, [uid, alert]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePriceAlert(String? uid, String? alertId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePriceAlert, [uid, alertId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [HiveDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveDataSource extends _i1.Mock implements _i11.HiveDataSource {
  MockHiveDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSettings(_i8.UserSettingsModel? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i8.UserSettingsModel?> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i3.Future<_i8.UserSettingsModel?>.value(),
          )
          as _i3.Future<_i8.UserSettingsModel?>);

  @override
  _i3.Future<void> saveMarketPrices(
    Map<String, _i9.MarketPriceModel>? prices,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveMarketPrices, [prices]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, _i9.MarketPriceModel>> getMarketPrices() =>
      (super.noSuchMethod(
            Invocation.method(#getMarketPrices, []),
            returnValue: _i3.Future<Map<String, _i9.MarketPriceModel>>.value(
              <String, _i9.MarketPriceModel>{},
            ),
          )
          as _i3.Future<Map<String, _i9.MarketPriceModel>>);
}
